PACKAGE_TARNAME = papi
prefix = /home/garrett/workspace/sofa/papi/src/build
exec_prefix = ${prefix}
datarootdir = ${prefix}/share
datadir = ${datarootdir}/${PACKAGE_TARNAME}
DATADIR = $(DESTDIR)$(datadir)
LIBRARY = libpapi.a
PAPILIB = $(LIBRARY)
INCLUDE = -I. -I${prefix}/include
CC	= gcc
F77	= 
CC_R	= $(CC) -pthread
CFLAGS	=  -g -Wextra  -Wall -O1

